Update com.behringer.XAirEdit.yml
flathub/com.behringer.XAirEdit pull request #6
Opened 2021-09-25 03:58 UTC by thorhop

The URL has changed. Same file, they just removed the "x64" and "V" before "1.5" from the filename.

2021-09-25 09:28 UTC, thorhop commented
Whoopsie! org.freedesktop.Platform && Sdk are outdated. Switched to LTS freedesktop Platform/Sdk.

2021-09-26 11:50 UTC, thorhop commented
Ran it on my F35 (Silverlight). It opens and works beautifully (in particular with my Lenovo Yoga 520 touchscreen!) Will have to find someone who own's a Behringer XR16 or XR18 to see if connectivity works, but the app itself is up and running with no problems whatsoever.

![image](https://user-images.githubusercontent.com/1967775/134806477-75dbdf8d-82bf-4aed-ac9f-78c1261cdf33.png)

2021-09-26 12:35 UTC, TheEvilSkeleton commented on com.behringer.XAirEdit.yml
> +runtime-version: "20.08"
```suggestion
runtime-version: "21.08"
```

There's now 21.08 FYI.

2021-09-26 12:35 UTC, TheEvilSkeleton requested changes

2021-09-26 12:35 UTC, TheEvilSkeleton commented on com.behringer.XAirEdit.yml
> +runtime-version: "20.08"
```suggestion
runtime-version: "21.08"
```

There's now 21.08 FYI.

2021-09-26 12:49 UTC, thorhop commented
Just tested it again on my system and works just fine with newer runtime :)

2021-09-27 08:55 UTC, valentindavid commented
Thank you very much @thorhop, I will review and test it tomorrow.

2021-09-28 12:38 UTC, valentindavid commented
@thorhop Thank you, that works. I will merge that. We will however need to update `com.behringer.XAirEdit.metainfo.xml`

2021-09-28 12:38 UTC, merged

2021-09-28 12:40 UTC, valentindavid commented
> We will however need to update com.behringer.XAirEdit.metainfo.xml
Nevermind, it is still 1.5. I will look at updating it.